# Version 1.000 
# Ansible 2.7.7

---
- hosts: all
  gather_facts: yes
  user: cloud_user
  become: yes
  vars:
    k8s_version: "1.19.3-00"

  tasks:
   - name: install remote apt deps
     apt: name="{{ item }}" state=present update_cache=true
     with_items:
       - apt-transport-https
       - ca-certificates
       - gnupg2
       - software-properties-common

   - name: add Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: add Kubernetes repo
     apt_repository:
       filename: 'kubernetes'
#        repo: deb http://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release }}  main
       repo: deb https://apt.kubernetes.io/ kubernetes-xenial  main
       state: present

   - name: Swap off live
     command: swapoff -a

   - name: Swap off fstab
     replace:
       path: /etc/fstab
       regexp: '^(.*\bswap\b.*)'
       replace: '#\1'

   - name: install kubelet
     apt:
       name: kubelet={{ k8s_version }}
       state: present
       update_cache: true

   - name: install kubeadm
     apt:
       name: kubeadm={{ k8s_version }}
       state: present

