# Version 1.000 
# Ansible 2.7.7
# K8s master only

---
- hosts: all
  become: yes
  become_user: root
  vars:
    k8s_version: "1.19.3-00"
  tasks:
   - name: install kubectl
     apt:
       name: kubectl={{ k8s_version }}
       state: present
       force: yes

